# Generated by Django 2.0 on 2018-04-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=None, max_length=1000, upload_to=''),
        ),
    ]
