# Generated by Django 2.0 on 2018-04-23 10:33

from django.db import migrations, models
import ngoma.models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0002_auto_20180423_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.ImageField(upload_to='album_logos/', validators=[ngoma.models.file_size]),
        ),
    ]
