# Generated by Django 2.0 on 2018-06-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0003_auto_20180423_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='activity',
            field=models.CharField(choices=[('sleeping', 'sleeping'), ('joking', 'joking'), ('coding', 'coding'), ('driving', 'driving'), ('parting', 'partying')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='mood',
            field=models.CharField(choices=[('happy', 'happy'), ('sad', 'sad'), ('angry', 'angry'), ('spiritual', 'spiritual')], default='happy', max_length=100),
        ),
        migrations.AddField(
            model_name='fromexternalsites',
            name='genre',
            field=models.CharField(choices=[('Reggae', 'Reggae'), ('Dancehall', 'Dancehall'), ('Hip Hop|Rap', 'Hip Hop|Rap'), ('Country', 'Country'), ('Rnb', 'Rnb'), ('Bongo', 'Bongo'), ('Rock and Roll', 'Rock and Roll')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Reggae', 'Reggae'), ('Dancehall', 'Dancehall'), ('Hip Hop|Rap', 'Hip Hop|Rap'), ('Country', 'Country'), ('Rnb', 'Rnb'), ('Bongo', 'Bongo'), ('Rock and Roll', 'Rock and Roll')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='yes', max_length=250),
            preserve_default=False,
        ),
    ]
