# Generated by Django 2.0 on 2018-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0004_auto_20180626_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='activity',
            field=models.CharField(choices=[('sleeping', 'sleeping'), ('joking', 'joking'), ('coding', 'coding'), ('driving', 'driving'), ('parting', 'partying')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='fromexternalsites',
            name='genre',
            field=models.CharField(choices=[('Reggae', 'Reggae'), ('Dancehall', 'Dancehall'), ('Hip Hop|Rap', 'Hip Hop|Rap'), ('Country', 'Country'), ('Rnb', 'Rnb'), ('Bongo', 'Bongo'), ('Rock and Roll', 'Rock and Roll')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Reggae', 'Reggae'), ('Dancehall', 'Dancehall'), ('Hip Hop|Rap', 'Hip Hop|Rap'), ('Country', 'Country'), ('Rnb', 'Rnb'), ('Bongo', 'Bongo'), ('Rock and Roll', 'Rock and Roll')], default=None, max_length=100),
        ),
    ]
