# Generated by Django 2.0 on 2018-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0005_auto_20180626_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='activity',
            field=models.CharField(choices=[('sleeping', 'sleeping'), ('joking', 'joking'), ('coding', 'coding'), ('driving', 'driving'), ('parting', 'partying'), ('general', 'general')], default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='mood',
            field=models.CharField(choices=[('happy', 'happy'), ('sad', 'sad'), ('angry', 'angry'), ('spiritual', 'spiritual'), ('general', 'general')], default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='fromexternalsites',
            name='genre',
            field=models.CharField(choices=[('Reggae', 'Reggae'), ('Dancehall', 'Dancehall'), ('Hip Hop|Rap', 'Hip Hop|Rap'), ('Country', 'Country'), ('Rnb', 'Rnb'), ('Bongo', 'Bongo'), ('Rock and Roll', 'Rock and Roll'), ('general', 'general')], default='general', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Reggae', 'Reggae'), ('Dancehall', 'Dancehall'), ('Hip Hop|Rap', 'Hip Hop|Rap'), ('Country', 'Country'), ('Rnb', 'Rnb'), ('Bongo', 'Bongo'), ('Rock and Roll', 'Rock and Roll'), ('general', 'general')], default='general', max_length=100),
        ),
    ]
