# Generated by Django 2.0 on 2018-07-04 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0006_auto_20180704_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='fromexternalsites',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='fromexternalsites',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='song',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
