# Generated by Django 2.0 on 2018-07-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0007_auto_20180704_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover',
        ),
        migrations.AlterField(
            model_name='fromexternalsites',
            name='genre',
            field=models.CharField(choices=[('Reggae', 'Reggae'), ('Dancehall', 'Dancehall'), ('Hip Hop|Rap', 'Hip Hop|Rap'), ('Country', 'Country'), ('Rnb', 'Rnb'), ('Bongo', 'Bongo'), ('Rock and Roll', 'Rock and Roll'), ('General', 'General')], default='general', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Reggae', 'Reggae'), ('Dancehall', 'Dancehall'), ('Hip Hop|Rap', 'Hip Hop|Rap'), ('Country', 'Country'), ('Rnb', 'Rnb'), ('Bongo', 'Bongo'), ('Rock and Roll', 'Rock and Roll'), ('General', 'General')], default='general', max_length=100),
        ),
    ]
