# Generated by Django 2.0 on 2018-07-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0008_auto_20180705_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
    ]
